name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.9'
      - run: python -m pip install --upgrade pip 
      
      - name: Install theme
        run: |
          pip install mkdocs-material==7.1.3 mkdocs-macros-plugin==0.5.5 \
                      mkdocs-markdownextradata-plugin==0.2.4 mkdocs-minify-plugin==0.4.0 mkdocs-material-extensions==1.0.1

      - name: Build docs
        run:  |
          git clean -f -d -x
          mkdocs build -c

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.9' 
      - run: python -m pip install --upgrade pip
      - name: Install theme 
        run: | 
          pip install mkdocs-material==7.1.3
          pip install mkdocs-macros-plugin==0.5.5 mkdocs-markdownextradata-plugin==0.2.4 mkdocs-minify-plugin==0.4.0 mkdocs-material-extensions==1.0.1
      - name: Deploy docs
        run: |
          mkdocs gh-deploy -c --force
          mkdocs --version
